### ISSUE TITLE
How do you specify the number of days to push out due date?

### ISSUE THREAD

**Issue by jack1729** [jclwilson/kanboard-plugin-assignduedate#1]
I would like to have a default due date of 5 days.

**Comment by jkwlsn** [comment]
Hi there,

you set the due date when you add the automatic action.

First go to: **Project Settings** > **Automatic Actions** > **Add a new action**

Then, choose the plugin:

![screenshot_2018-03-27_13-46-12](https://user-images.githubusercontent.com/3199935/37968182-5abbf6bc-31c5-11e8-8878-465e3a6b68f0.png)

Then choose the event:

![screenshot_2018-03-27_13-46-24](https://user-images.githubusercontent.com/3199935/37968245-8270e05a-31c5-11e8-936e-7288d7f9831c.png)

Then set the number of days, here I've filled in 5 for five days:

![screenshot_2018-03-27_13-43-36](https://user-images.githubusercontent.com/3199935/37968032-f88d5594-31c4-11e8-8d07-1786939a7fce.png)

Any card moved to the column **Outbox** will now have a due date **5 days from the current time**.
